#!/bin/sh

### cd /to-this-directory/Tools/Scripts/macos

SCRIPT_DIR="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
LANGUAGES="$SCRIPT_DIR/../../../Languages"


### Store 
#open -a Numbers "$LANGUAGES/Afrikaans/tsv/Afrikaans_af_appstore.tsv"
#open -a Numbers "$LANGUAGES/Arabic/tsv/Arabic_ar_appstore.tsv"
#open -a Numbers "$LANGUAGES/Bhojpuri/tsv/Bhojpuri_bho_appstore.tsv"
open -a Numbers "$LANGUAGES/Bulgarian/tsv/Bulgarian_bg_appstore.tsv"
#open -a Numbers "$LANGUAGES/Chinese_HongKong/tsv/Chinese_HongKong_zh_HK_appstore.tsv"
#open -a Numbers "$LANGUAGES/Chinese_Simplified/tsv/Chinese_Simplified_zh_Hans_appstore.tsv"
open -a Numbers "$LANGUAGES/Chinese_Traditional/tsv/Chinese_Traditional_zh_Hant_appstore.tsv"
#open -a Numbers "$LANGUAGES/Czech/tsv/Czech_cs_appstore.tsv"
#open -a Numbers "$LANGUAGES/Danish/tsv/Danish_da_appstore.tsv"
#open -a Numbers "$LANGUAGES/Dutch/tsv/Dutch_nl_appstore.tsv"
#open -a Numbers "$LANGUAGES/English_GB/tsv/English_GB_en-GB_appstore.tsv"
open -a Numbers "$LANGUAGES/English_US/tsv/English_US_en_appstore.tsv"
#open -a Numbers "$LANGUAGES/Estonian/tsv/Estonian_et_appstore.tsv"
#open -a Numbers "$LANGUAGES/Finnish/tsv/Finnish_fi_appstore.tsv"
open -a Numbers "$LANGUAGES/French/tsv/French_fr_appstore.tsv"
#open -a Numbers "$LANGUAGES/French_Canada/tsv/French_Canada_fr_CA_appstore.tsv"
#open -a Numbers "$LANGUAGES/Georgian/tsv/Georgian_ka_appstore.tsv"
open -a Numbers "$LANGUAGES/German/tsv/German_de_appstore.tsv"
open -a Numbers "$LANGUAGES/Greek/tsv/Greek_el_appstore.tsv"
#open -a Numbers "$LANGUAGES/Hebrew/tsv/Hebrew_he_appstore.tsv"
#open -a Numbers "$LANGUAGES/Hindi/tsv/Hindi_hi_appstore.tsv"
#open -a Numbers "$LANGUAGES/Hungarian/tsv/Hungarian_hu_appstore.tsv"
open -a Numbers "$LANGUAGES/Italian/tsv/Italian_it_appstore.tsv"
#open -a Numbers "$LANGUAGES/Japanese/tsv/Japanese_ja_appstore.tsv"
#open -a Numbers "$LANGUAGES/Kannada/tsv/Kannada_kn_appstore.tsv"
#open -a Numbers "$LANGUAGES/Korean/tsv/Korean_ko_appstore.tsv"
#open -a Numbers "$LANGUAGES/Lithuanian/tsv/Lithuanian_lt_appstore.tsv"
#open -a Numbers "$LANGUAGES/Mongolian/tsv/Mongolian_mn_appstore.tsv"
#open -a Numbers "$LANGUAGES/Norwegian_nb/tsv/Norwegian_nb_appstore.tsv"
#open -a Numbers "$LANGUAGES/Persian/tsv/Persian_fa_appstore.tsv"
#open -a Numbers "$LANGUAGES/Polish/tsv/Polish_pl_appstore.tsv"
open -a Numbers "$LANGUAGES/Portuguese/tsv/Portuguese_pt_appstore.tsv"
#open -a Numbers "$LANGUAGES/Portuguese_Brazil/tsv/Portuguese_pt_BR_appstore.tsv"
#open -a Numbers "$LANGUAGES/Portuguese_Portugal/tsv/Portuguese_pt_PT_appstore.tsv"
open -a Numbers "$LANGUAGES/Romanian/tsv/Romanian_ro_appstore.tsv"
open -a Numbers "$LANGUAGES/Russian/tsv/Russian_ru_appstore.tsv"
#open -a Numbers "$LANGUAGES/Serbian_Cyrillic/tsv/Serbian_Cyrillic_sr_appstore.tsv"
#open -a Numbers "$LANGUAGES/Serbian_Latin/tsv/Serbian_Latin_sr_Latn_appstore.tsv"
#open -a Numbers "$LANGUAGES/Slovak/tsv/Slovak_sk_appstore.tsv"
#open -a Numbers "$LANGUAGES/Slovenian/tsv/Slovenian_sl_appstore.tsv"
open -a Numbers "$LANGUAGES/Spanish/tsv/Spanish_es_appstore.tsv"
#open -a Numbers "$LANGUAGES/Swedish/tsv/Swedish_sv_appstore.tsv"
#open -a Numbers "$LANGUAGES/Thai/tsv/Thai_th_appstore.tsv"
#open -a Numbers "$LANGUAGES/Turkish/tsv/Turkish_tr_appstore.tsv"
#open -a Numbers "$LANGUAGES/Vietnamese/tsv/Vietnamese_vi_appstore.tsv"

