#!/bin/sh

### cd /to-this-directory/Tools/Scripts/macos
### .//OpenDroidXml_Current_COTEditor.sh

SCRIPT_DIR="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
LANGUAGES="$SCRIPT_DIR/../../../Languages"

## current: 11 files

#open -a CotEditor "$LANGUAGES/Afrikaans/android/values-af/strings.xml"
#open -a CotEditor "$LANGUAGES/Arabic/android/values-ar/strings.xml"
#open -a CotEditor "$LANGUAGES/Bhojpuri/android/values-bho/strings.xml"
open -a CotEditor "$LANGUAGES/Bulgarian/android/values-bg/strings.xml"
#open -a CotEditor "$LANGUAGES/Chinese_HongKong/android/values-HongKong_zh_HK/strings.xml"
#open -a CotEditor "$LANGUAGES/Chinese_Simplified/android/values-Simplified_zh_Hans/strings.xml"
open -a CotEditor "$LANGUAGES/Chinese_Traditional/android/values-zh/strings.xml" # Traditional _Hant
#open -a CotEditor "$LANGUAGES/Czech/android/values-cs/strings.xml"
#open -a CotEditor "$LANGUAGES/Danish/android/values-da/strings.xml"
#open -a CotEditor "$LANGUAGES/Dutch/android/values-nl/strings.xml"
#open -a CotEditor "$LANGUAGES/English_GB/android/values-en-rGB/strings.xml"
open -a CotEditor "$LANGUAGES/English_US/android/values/strings.xml"
#open -a CotEditor "$LANGUAGES/Estonian/android/values-et/strings.xml"
#open -a CotEditor "$LANGUAGES/Finnish/android/values-fi/strings.xml"
open -a CotEditor "$LANGUAGES/French/android/values-fr/strings.xml"
#open -a CotEditor "$LANGUAGES/French_Canada/android/values-Canada_fr_CA/strings.xml"
#open -a CotEditor "$LANGUAGES/Georgian/android/values-ka/strings.xml"
open -a CotEditor "$LANGUAGES/German/android/values-de/strings.xml"
open -a CotEditor "$LANGUAGES/Greek/android/values-el/strings.xml"
#open -a CotEditor "$LANGUAGES/Hebrew/android/values-he/strings.xml"
#open -a CotEditor "$LANGUAGES/Hindi/android/values-hi/strings.xml"
#open -a CotEditor "$LANGUAGES/Hungarian/android/values-hu/strings.xml"
open -a CotEditor "$LANGUAGES/Itialian/android/values-it/strings.xml"
#open -a CotEditor "$LANGUAGES/Japanese/android/values-ja/strings.xml"
#open -a CotEditor "$LANGUAGES/Kannada/android/values-kn/strings.xml"
#open -a CotEditor "$LANGUAGES/Korean/android/values-ko/strings.xml"
#open -a CotEditor "$LANGUAGES/Lithuanian/android/values-lt/strings.xml"
#open -a CotEditor "$LANGUAGES/Mongolian/android/values-mn/strings.xml"
#open -a CotEditor "$LANGUAGES/Norwegian_nb/android/values-nb/strings.xml"
#open -a CotEditor "$LANGUAGES/Persian/android/values-fa/strings.xml"
#open -a CotEditor "$LANGUAGES/Polish/android/values-pl/strings.xml"
open -a CotEditor "$LANGUAGES/Portuguese/android/values-pt/strings.xml"
#open -a CotEditor "$LANGUAGES/Portuguese_Brazil/android/values-pt_BR/strings.xml"
#open -a CotEditor "$LANGUAGES/Portuguese_Portugal/android/values-pt_PT/strings.xml"
open -a CotEditor "$LANGUAGES/Romanian/android/values-ro/strings.xml"
open -a CotEditor "$LANGUAGES/Russian/android/values-ru/strings.xml"
#open -a CotEditor "$LANGUAGES/Serbian_Cyrillic/android/values-Cyrillic_sr/strings.xml"
#open -a CotEditor "$LANGUAGES/Serbian_Latin/android/values-Latin_sr_Latn/strings.xml"
#open -a CotEditor "$LANGUAGES/Slovak/android/values-sk/strings.xml"
#open -a CotEditor "$LANGUAGES/Slovenian/android/values-sl/strings.xml"
open -a CotEditor "$LANGUAGES/Spanish/android/values-es/strings.xml"
#open -a CotEditor "$LANGUAGES/Swedish/android/values-sv/strings.xml"
#open -a CotEditor "$LANGUAGES/Thai/android/values-th/strings.xml"
#open -a CotEditor "$LANGUAGES/Turkish/android/values-tr/strings.xml"
#open -a CotEditor "$LANGUAGES/Vietnamese/android/values-vi/strings.xml"
