#!/bin/sh

### cd /to-this-directory/Tools/Scripts/macos
### ./OpenDroidXml_Current_BBEdit.sh

SCRIPT_DIR="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
LANGUAGES="$SCRIPT_DIR/../../../Languages"

## current: 12 files

#open -a BBEdit "$LANGUAGES/Afrikaans/android/values-af/strings.xml"
#open -a BBEdit "$LANGUAGES/Arabic/android/values-ar/strings.xml"
#open -a BBEdit "$LANGUAGES/Bhojpuri/android/values-bho/strings.xml"
open -a BBEdit "$LANGUAGES/Bulgarian/android/values-bg/strings.xml"
#open -a BBEdit "$LANGUAGES/Chinese_HongKong/android/values-zh-HK/strings.xml"
#open -a BBEdit "$LANGUAGES/Chinese_Simplified/android/values-zh-Hans/strings.xml"
open -a BBEdit "$LANGUAGES/Chinese_Traditional/android/values-zh/strings.xml" # Traditional _Hant
#open -a BBEdit "$LANGUAGES/Czech/android/values-cs/strings.xml"
#open -a BBEdit "$LANGUAGES/Danish/android/values-da/strings.xml"
#open -a BBEdit "$LANGUAGES/Dutch/android/values-nl/strings.xml"
#open -a BBEdit "$LANGUAGES/English_GB/android/values-en-rGB/strings.xml"
open -a BBEdit "$LANGUAGES/English_US/android/values/strings.xml"
#open -a BBEdit "$LANGUAGES/Estonian/android/values-et/strings.xml"
#open -a BBEdit "$LANGUAGES/Finnish/android/values-fi/strings.xml"
open -a BBEdit "$LANGUAGES/French/android/values-fr/strings.xml"
#open -a BBEdit "$LANGUAGES/French_Canada/android/values-fr-CA/strings.xml"
#open -a BBEdit "$LANGUAGES/Georgian/android/values-ka/strings.xml"
open -a BBEdit "$LANGUAGES/German/android/values-de/strings.xml"
open -a BBEdit "$LANGUAGES/Greek/android/values-el/strings.xml"
#open -a BBEdit "$LANGUAGES/Hebrew/android/values-he/strings.xml"
#open -a BBEdit "$LANGUAGES/Hindi/android/values-hi/strings.xml"
#open -a BBEdit "$LANGUAGES/Hungarian/android/values-hu/strings.xml"
open -a BBEdit "$LANGUAGES/Itialian/android/values-it/strings.xml"
#open -a BBEdit "$LANGUAGES/Japanese/android/values-ja/strings.xml"
#open -a BBEdit "$LANGUAGES/Kannada/android/values-kn/strings.xml"
#open -a BBEdit "$LANGUAGES/Korean/android/values-ko/strings.xml"
#open -a BBEdit "$LANGUAGES/Lithuanian/android/values-lt/strings.xml"
#open -a BBEdit "$LANGUAGES/Mongolian/android/values-mn/strings.xml"
#open -a BBEdit "$LANGUAGES/Norwegian_nb/android/values-nb/strings.xml"
#open -a BBEdit "$LANGUAGES/Persian/android/values-fa/strings.xml"
open -a BBEdit "$LANGUAGES/Polish/android/values-pl/strings.xml"
open -a BBEdit "$LANGUAGES/Portuguese/android/values-pt/strings.xml"
#open -a BBEdit "$LANGUAGES/Portuguese_Brazil/android/values-pt-BR/strings.xml"
#open -a BBEdit "$LANGUAGES/Portuguese_Portugal/android/values-pt-PT/strings.xml"
open -a BBEdit "$LANGUAGES/Romanian/android/values-ro/strings.xml"
open -a BBEdit "$LANGUAGES/Russian/android/values-ru/strings.xml"
#open -a BBEdit "$LANGUAGES/Serbian_Cyrillic/android/values-sr/strings.xml"
#open -a BBEdit "$LANGUAGES/Serbian_Latin/android/values-sr-Latn/strings.xml"
#open -a BBEdit "$LANGUAGES/Slovak/android/values-sk/strings.xml"
#open -a BBEdit "$LANGUAGES/Slovenian/android/values-sl/strings.xml"
open -a BBEdit "$LANGUAGES/Spanish/android/values-es/strings.xml"
#open -a BBEdit "$LANGUAGES/Swedish/android/values-sv/strings.xml"
#open -a BBEdit "$LANGUAGES/Thai/android/values-th/strings.xml"
#open -a BBEdit "$LANGUAGES/Turkish/android/values-tr/strings.xml"
#open -a BBEdit "$LANGUAGES/Vietnamese/android/values-vi/strings.xml"
